---
# check if /etc/hosts.deny exist, if yes, mv it to other name or remove it
# just in case it prevent client connecting
- name: remove /etc/host.deny file
  file: path=/etc/hosts.deny state=absent

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include overrides specific to RHEL 7.
  include_vars: RedHat-7.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == "7"

- name: Include overrides specific to Fedora.
  include_vars: Fedora.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == "Fedora"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: create server mount point
  file: path={{nfs_server_mount}} owner=root group=root state=directory mode=0755

- name: Ensure directories to export exist
  file: 'path="{{ item.strip().split()[0] }}" state=directory'
  with_items: "{{ nfs_exports }}"
  #notify: restart nfs

- name: Copy exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  register: nfs_exports_copy
  #notify: restart nfs

- name: Restart NFS immediately if exports are updated.
  service: "name={{ nfs_server_daemon }} state=restarted"
  when: nfs_exports_copy.changed

- name: Ensure nfs is running.
  service: "name={{ nfs_server_daemon }} state=started enabled=yes"
  #when: nfs_exports|length
