- hosts: sonar
  serial: 1
  remote_user: ec2-user
  #remote_user: vagrant
  sudo: yes
  vars:
    domain_crt: sonar
    domain_key: sonar

  pre_tasks:
    - set_fact:
        service_cmd: "/sbin/service"
      when: ansible_os_family == 'RedHat'
    - set_fact:
        service_cmd: "/usr/sbin/service"
      when: ansible_os_family == 'Debian'

  roles:
    - oracle_java8
    - nginx_proxy
    - sonar
    - { role:
          cron_jobs,
          cron_jobs: [
            {
              minute: "36",
              hour: "5",
              command: "{{service_cmd}}",
              args: "sonar start"
            },
            {
              minute: "57",
              hour: "19",
              command: "{{service_cmd}}",
              args: "sonar stop"
            },
            {
              minute: "58",
              hour: "19",
              command: "{{service_cmd}}",
              args: "postgresql stop"
            },
            {
              minute: "35",
              hour: "5",
              command: "{{service_cmd}}",
              args: "postgresql start"
            }
          ]
      }

  environment:
    http_proxy: http://id\pass@your.proxy.name:port
    https_proxy: http://id\pass@your.proxy.name:port
