- name: Docker Compose are present
  get_url:
    url: https://github.com/docker/compose/releases/download/1.4.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    validate_certs: no
  tags: [compose]

- name: Docker Compose permission are set
  file:
    path: /usr/local/bin/docker-compose
    mode: 0755
  tags: [compose]
