---
#__jenkins_repo_url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
__jenkins_repo_url: http://nectar-downloads.cloudbees.com/jenkins-enterprise/1.642/rpm/jenkins.repo
#__jenkins_repo_key_url: http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key
__jenkins_repo_key_url: http://nectar-downloads.cloudbees.com/jenkins-enterprise/1.642/rpm/cloudbees.com.key
jenkins_init_file: /etc/sysconfig/jenkins
jenkins_http_port_param: JENKINS_PORT

