---
### this does not work on SSA environment
#- include: setup-RedHat.yml
#  when: ansible_os_family == 'RedHat'


- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

## if install epel-release not work, do this instead(rhel-6):
#  wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm --no-check-certificate
# sudo rpm -Uvh epel-release-latest-6.noarch.rpm
- name: install epel-release repo
  yum: name=epel-release state=present
  when: ansible_os_family == 'RedHat'

- name: install nodejs and npm
  yum: name=nodejs,npm state=present
  when: ansible_os_family == 'RedHat'

- name: Define nodejs_install_npm_user
  set_fact:
    #nodejs_install_npm_user: "{{ ansible_ssh_user }}"
    nodejs_install_npm_user: "root"
  when: nodejs_install_npm_user is not defined

- name: copy global npmrc file
  template: src=npmrc.j2 dest=/usr/etc/npmrc owner=root group=root mode=0755 backup=yes

## TODO: Remove this task after Ansible 2.x npm module bug is fixed. See:
## https://github.com/ansible/ansible-modules-extras/issues/1375
#- name: Ensure forever is installed (to run Node.js apps).
#  npm: name=forever global=yes state=present
#  become: yes
#  become_user: "{{ nodejs_install_npm_user }}"
#  when: nodejs_forever

#- name: Ensure forever is at the latest release.
#  npm: name=forever global=yes state=latest
#  become: yes
#  become_user: "{{ nodejs_install_npm_user }}"
#  when: nodejs_forever

# TODO: Remove this task after Ansible 2.x npm module bug is fixed. See:
# https://github.com/ansible/ansible-modules-extras/issues/1375
- name: Ensure npm global packages are installed.
  npm:
    name: "{{ item.name }}"
    version: "{{ item.version | default('') }}"
    global: yes
    state: present
  become: yes
  become_user: "{{ nodejs_install_npm_user }}"
  with_items: "{{ nodejs_npm_global_packages }}"

- name: Ensure npm global packages are at the latest release.
  npm:
    name: "{{ item.name }}"
    version: "{{ item.version | default('') }}"
    global: yes
    state: latest
  become: yes
  become_user: "{{ nodejs_install_npm_user }}"
  with_items: "{{ nodejs_npm_global_packages }}"
