---
# Set the version of Node.js to install (e.g. "0.10", "0.12", "4.x", "5.x").
# Version numbers from Nodesource: https://github.com/nodesource/distributions
nodejs_version: "5.x"

# The user for whom the npm packages will be installed.
# nodejs_install_npm_user: username

# Install forever, which is useful for running Node.js apps.
nodejs_forever: true

# Define a list of global packages to be installed with NPM.
nodejs_npm_global_packages: 
#  # Install a specific version of a package.
#  - name: jslint
#    version: 0.9.3
#  # Install the latest stable release of a package.
#  - name: node-sass
  # Install the latest stable release of a package.
  - name: grunt

proxy_url: http://access.lb.ssa.gov:80
registry_url: http://nexus.ba.ssa.gov:8082/nexus/content/groups/npm-all/
