nexus_download_url: "http://download.sonatype.com/clm/server/sonatype-clm-server-1.15.0-02-bundle.tar.gz"
nexus_package: "sonatype-clm-server-1.15.0-02-bundle.tar.gz"
nexus_os_user: "clmserver"
nexus_os_group: "clmserver"
nexus_installation_dir: "/opt/tools/sonatype-clm-server-{{nexus_version}}"
nexus_home: "/opt/tools/sonatype-clm-server"
nexus_init_src: "sonatype-clm-server.j2"
nexus_init_dest: "/etc/init.d/sonatype-clm-server"
nexus_service: "sonatype-clm-server"
