---

- name: include postgresql-Debian.yml
  include: postgresql-Debian.yml
  when: ansible_os_family == "Debian"

- name: include postgresql-RedHat.yml
  include: postgresql-RedHat.yml
  when: ansible_os_family == "RedHat"

- name: postgresql | Create sonar postgresql user
  postgresql_user: 
     name="{{jdbc_user}}"
     password="{{jdbc_pass}}"
  sudo_user: "{{ postgres_sudo_user }}"
  notify: restart bitbucket
  tags: postgresql_server

- name: postgresql | Create sonar postgresql database
  postgresql_db: 
     name="{{jdbc_db}}"
     owner="{{jdbc_user}}"
     encoding='UTF-8'
     lc_collate='en_US.UTF-8'
     lc_ctype='en_US.UTF-8'
     template='template0'
  sudo_user: "{{ postgres_sudo_user }}"
  notify: restart bitbucket
  tags: postgresql_server

