---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

#- name: Configure Elasticsearch-2.x.
#  lineinfile: >
#    dest=/etc/elasticsearch/elasticsearch.yml
#    regexp="{{ item.regexp }}"
#    line="{{ item.line }}"
#    state=present
#  with_items:
#    - { regexp: '^script\.inline', line: 'script.inline: on' }
#    - { regexp: '^script\.indexed', line: 'script.indexed: on' }
#    - { regexp: 'network\.host', line: 'network.host: localhost' }
#  notify: restart elasticsearch

- name: Configure Elasticsearch-1.7.x.
  lineinfile: >
    dest=/etc/elasticsearch/elasticsearch.yml
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { regexp: '^#bootstrap\.mlockall', line: 'bootstrap.mlockall: true' }
    - { regexp: '^#http\.port', line: 'http.port: 9201' }
    - { regexp: '^#discovery\.zen\.ping\.multicast\.enabled', line: 'discovery.zen.ping.multicast.enabled: false'}
  notify: restart elasticsearch

- name: Start Elasticsearch.
  service: name=elasticsearch state=started enabled=yes
