---

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags: ['docker']

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  tags: ['docker']

